### ISSUE TITLE
DSL компонентов: неверный parentMeta

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1037]
Root компонент в нашем десктоп приложении:

<img width="822" alt="image" src="https://github.com/V4Fire/Client/assets/46344555/ee3f8efc-6eec-45ac-8e05-536738b3a464">

Дублируется i-static-page, i-page.

Это поведение вызвано переопределением компонента в слое. Необходимо в parentMeta показать информацию, что это переопределение.

**Comment by kobezzza** [comment]
Исправлено
