### ISSUE TITLE
stateless слайдер scroll snap css

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#1039]
Появилась возможность реализовать слайдер, похожий на наш, с использованием нативного API "scroll snap" CSS. Вот пример реализации: [ссылка на пример](https://codepen.io/newinweb/pen/EpPgdR).

Что нужно сделать:

1. Добавить глобальный хелпер, который будет реализовывать обертку слайдера на основе CSS "scroll snap". Можно создать класс, например, "g-slider", который будет добавлять необходимую логику, или использовать вспомогательную функцию "SS", которая поместит содержимое в эту обертку.

2. Важным дополнительным моментом является рассмотрение компонента "b-slider" и добавление ему дополнительного режима работы, когда включается CSS "scroll snap" и отключается JS обработка touch событий, в зависимости от определенного параметра, например, передаваемого свойства "scrollSnap: true".

**Comment by shining-mind** [comment]
Implemented in #1095
