### ISSUE TITLE
Неккоректная работа IntersectionWatcher из-за некорректной выборки IO из пула

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#1049]
```ts
test.only(
	[
		'the watcher should be able to observe single element with different options twice'
	].join(' '),

	async ({page}) => {
		const intersectionResults = await page.evaluateHandle<string[]>(() => []);

		await Utils.collectPageLogs(page);
		
		await getObserver(engine).evaluate((observer, {target, intersectionResults}) => {
			setTimeout(() => {
				// once не влияет на результат		
				observer.watch(target, {delay: 0, once: true, threshold: 0.5}, () => {
					intersectionResults.push('first');
				});
			}, 50);
			

			observer.watch(target, {delay: 1, threshold: 0.5}, () => {
				intersectionResults.push('second');
			});

		}, {target, intersectionResults});

		await scrollBy(page, {top: 100});
		await page.waitForTimeout(1000);

		await Utils.printPageLogs(page);

		console.log(await intersectionResults.evaluate((results) => results));
	}
);
```

В таком тесте массив будет содержать только 'second'.

Кажется, это происходит из-за повторного использования IntersectionObserver, так как сейчас IO используется один и тот же для одного элемента; но так не должно быть. Из-за этого не происходит второго срабатывания. (Это нужно проверить на самом деле, но, похоже, это так).

Логика с пулом должна быть такая:

[IO1 с [el1], IO2 с [el2], IO3 с [el3]]

1. Регистрируем повторно el1.
2. Ищем ближайший подходящий (в рамках допустимого разброса) по threshold IO.
3. Выбираем IO1.
4. Он нам подходит по threshold, но не подходит, так как el1 уже зарегистрирован в нем.
5. Выбираем IO2, который подходит по threshold, и в нем нет el1.
6. Регистрируем el1 в IO2.

Способ проще:

При выборе из пула смотреть прикреплен ли к этому IO этот el, если нет - то используем, если да - создаем новый.

-----

Детали:
Если указать threshold 0.6, то все начинает работать.

**Comment by Dimeliora** [comment]
Создание нового экземпляра IO происходит, если существующие не подходят по зарегистрированным параметрам (хэш от настроек, сюда входят значения threshold, trackVisibility, остальные параметры исключаются, delay в нашей реализации обрабатывается отдельно, для совместимости API обеих стратегий). На самом деле, не важно, наблюдает ли инстанс за данным элементом (к тому же API IO этого не позволяет проверить), потому что регистрируемый обработчик всегда один - метод onObserver. При пересечении как раз внутри него происходит обход всех зарегистрированных вотчеров для пересекаемого элемента (хранятся в соответствующих map) и выполнение их обработчиков.
По приведённому тест-кейсу: в данном случае экземпляр IO действительно будет один на оба наблюдателя, а отсутствие второго срабатывания объясняется следующим. Так как первый вотчер регистрируется отложенно, на момент регистрации скролл уже случился и элемент находится во вьюпорте. В случае, когда у вотчеров различаются значения threshold, происходит регистрация нового экземпляра IO, а у метода observe экземпляра IO есть сайд-эффект - при первоначальном вызове для конкретного элемента сразу же происходит выполнение зарегистрированного обработчика. Поэтому тест проходит, если значения порога различны.
Таким образом, причина падения теста - второй вотчер регистрируется после скролла, повторный вызов `observer.value.observe(watcher.target)` (и observer, и target одни и те же) не вызывает обработчик. То есть нужно подождать регистрации второго вотчера перед скроллом.
Впрочем, всё равно имеем неконсистентность - у стратегии heightmap поведение иное, обработчик срабатывает, если на момент регистрации элемент находится в поле видимости, и порядок выполнения обработчиков иной (у heightmap при инициализации вотчера по умолчанию установлена задержка в 100мс).

**Comment by bonkalol** [comment]
@Dimeliora приликнуй мр сюда и закрывай

**Comment by Dimeliora** [comment]
Исправлено: [#1064](https://github.com/V4Fire/Client/pull/1064)

**Comment by Dimeliora** [comment]
Исправлено: [#1064](https://github.com/V4Fire/Client/pull/1064)
