### ISSUE TITLE
1 декоратор на несколько инстансов компонента

### ISSUE THREAD

**Issue by Razdva122** [V4Fire/Client#1063]
Пример с debounce
```
class Component {
  @debounce(50)
  protected foo(): void {
    console.log('foo', this);
  }
}
```

Если на странице будет создано несколько компонентов, то все методы `foo` будут обернуты одним `debounce`, а значит вызовы `foo` в одном компоненте будут глушить вызов `foo` в другом

**Comment by kobezzza** [comment]
Исправлено
