### ISSUE TITLE
Проблемы v-image

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1079]
Рассмотрим на примере:

```
< img.&__banner-img &
  v-image = {
	  src: slot.images.hdpi,
	  srcset: {"1.5x": slot.images.xhdpi, "2x": slot.images.xxhdpi, "3x": slot.images.xxxhdpi},
	  onLoad: (node) => registerAnalytics(node.parentNode, banner, slot, {bannerIndex, slotIndex}),
	  onError: (node) => onImageLoadFailed(node.parentNode)
  } |
  
  :width = banner.type === 'banner' ? imgWidth : '' |
  :height = banner.type === 'banner' ? imgHeight : '' |
  :sizes = banner.type === 'banner' ? imgSizes : '' |
  
  alt = Изображение баннера |
  draggable = false |
  
  -test-ref = banner-img |
  
  @load = onImageBannerLoad
.		
```

### Магия под капотом

Изменяется разметка под капотом - это не декларативно.
Если необходимо задать стилизацию изображению, то происходит раскрытие внутреннего API:

```styl
&__banner-img
  img 
    display block
    width 100%
```

Как сайд-эффект: у разработчика может возникнуть желание повесить эту директиву на тег img (наш пример).
Свойства `width, height, sizes, alt, draggable` и `@load` не будут проброшены на сгенерированный img.

### Постоянно изменяется DOM узел

Модификация vnode под капотом приводит к утечкам памяти. В примере мы регистрируем аналитику на полученный `node`, который постоянно меняется.

**Comment by bonkalol** [comment]
Поддерживаю, генерация узлов вместо этого узла может сломать ref, может сломать какие-либо другие директивы, все это приводит к необходимости создавать обертки и держать в уме логику генерации дополнительной разметки

**Comment by ann-arzamm** [comment]
Использование `v-image` в том числе требует всегда устанавливать руками `width 100%` для тега `img`. Раз это тег подшивается директивой, почему не сделать это дефолтным стилем?

**Comment by kobezzza** [comment]
> Использование v-image в том числе требует всегда устанавливать руками width 100% для тега img. Раз этот тег подшивается директивой, почему не сделать это дефолтным стилем?

Директива - не компонент, у ней нет стилей. А задавать стиль через style рисковано.

Решение очень простое на самом деле, завести g- стиль, например, g-image

```
< .g-image v-image = ...
```

**Comment by kobezzza** [comment]
> Поддерживаю, генерация узлов вместо этого узла может сломать ref, может сломать какие-либо другие директивы, все это приводит к необходимости создавать обертки и держать в уме логику генерации дополнительной разметки

Директива генерирует VDOM и не должна ломать ref и другую логику. Если это так, то заводите баги - поправим.

**Comment by shining-mind** [comment]
Для v-icon и v-image добавить исключения, если

1) v-image используется на тегах: `img`, `picture`, `object`.
2) v-icon используется на тегах: `svg`.

**Comment by shining-mind** [comment]
Поддержать draggable свойство для `img`
