### ISSUE TITLE
[v4v4] Не работает дефолное значение для `stageStore`

### ISSUE THREAD

**Issue by ann-arzamm** [V4Fire/Client#1113]
Предположим, что компонент оверрайдит поле `stageStore`с выставлением ему дефолтного значения:
`protected override stageStore: 'count' | 'toggle' = 'count';`

Проблема: в v4v3 дефолтное значение записывается в stage, v4v4 - нет. 

Замена `stageStore` на `stageProp` чинит проблему.

**Comment by shining-mind** [comment]
> Все дело в том, что stageStore слинкован с stageProp, т.е. при инициализации он берет значение пропса. Нужно придумать какой-нибудь способ оповещать разработчика о таких ситуациях.

Интересно почему в 3 версии это работало?

**Comment by kobezzza** [comment]
> > Все дело в том, что stageStore слинкован с stageProp, т.е. при инициализации он берет значение пропса. Нужно придумать какой-нибудь способ оповещать разработчика о таких ситуациях.
> 
> Интересно почему в 3 версии это работало?

Undefined behaviour :)

Но сейчас оно не работает и это корректное поведение.
