### ISSUE TITLE
Рефакторинг core/system-theme-extractor

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#1114]
Данному модулю нет места в core, т.к. все что лежит в core/ может быть использовано из любого места приложения, но по факту оно привязан к компоненту и сам модуль не имеет паблик АПИ (только интерфейсы). Кажется ему место как подмодуль src/`components/super/i-static-page/modules/theme`

**Comment by Gannicus91** [comment]
https://github.com/V4Fire/Client/pull/1116
