### ISSUE TITLE
[v4v4] В сборку не подключаются стили для компонентов внутри `loadModules`

### ISSUE THREAD

**Issue by ann-arzamm** [V4Fire/Client#1115]
Есть компонент, подключаемый на страницу внутри `loadModules`:

```
+= self.loadModules('b-foo')
  < b-foo
```

Если он не указан внутри `dependencies` в index.js страницы, то при сборке под android/ios его стили не попадают в сборку.
При явном указании в `dependencies`, стили подключаются.

**Comment by shining-mind** [comment]
By design при сборке стили и ассеты из асинхронных импортов в FATHTML в бандл не попадают, потому что это приводит к дублированию кода.

Потому для FATHTML надо указывать вручную все компоненты, которую загружаются асинхронно.
