### ISSUE TITLE
[v4v4] Обработчики событий в поле `$attrs`

### ISSUE THREAD

**Issue by geopr** [V4Fire/Client#1118]
В новой версии v4 в поле `this.$attrs` у компонента начали добавляться обработчики событий

```ss
< b-component @back = onBackClick
```

v3:
<img width="320" alt="Screenshot 2024-02-06 at 6 11 10 PM" src="https://github.com/V4Fire/Client/assets/65154994/c6e80ece-3080-4717-9c5e-aec4666f637d">
v4:
<img width="708" alt="Screenshot 2024-02-06 at 6 15 30 PM" src="https://github.com/V4Fire/Client/assets/65154994/1af6ffff-2b00-4ae2-8d52-8c17d0430d7f">

Это проводит к багам в местах, где родитель агрегирует в себе другие компоненты и пропускает их события через себя:

`b-global-header.ss`
```ss
< b-concrete-header &
  :v-attrs = $attrs |
  :dispatching = true
.
```
`page.ss`
```
< b-global-header &
  :selfDispatching = true |
  @event = handler
.
```
Получается, что обработчик прокинется в дочерний компонент шапки и вызовется два раза

**Comment by kobezzza** [comment]
Это не ошибка, просто Vue3 регистрирует обработчики как атрибуты. Тут либо добавить фильтрацию, либо посмотреть как сделано в bDynamicPage и сделать также.
