### ISSUE TITLE
[v4v4] Не срабатывает `submit` у функционального `b-form` 

### ISSUE THREAD

**Issue by ann-arzamm** [V4Fire/Client#1124]
Пример:
```
< b-tabs

< b-form @onSubmitStart = onSubmit		
  < b-button :type = 'submit' 
    Перейти
```
Описание примера:
На странице есть вкладки, переключение которых меняет `@field` поле. В зависимости от вкладки, `onSubmit` выполнит переход на разные страницы.

Пример демо страницы можно собрать в ветке `issues/1124`

Проблема: Если была изменена вкладка, то `submit` при нажатии на кнопку не срабатывает. 
Изменение `b-form` с функционального компонента на обычный чинит проблему.

**Comment by shining-mind** [comment]
TLDR: проблема в том, что теряется обработчик submit при изменение стейта родителя

**Comment by shining-mind** [comment]
Кажется проблема в кэшировании обработчиков: 
<img width="1111" alt="image" src="https://github.com/V4Fire/Client/assets/46344555/9dfa3e7f-335d-4c89-b026-ae72d22a00a8">

Сохраняется ctx от предыдущего инстанса функционального компонента, а метод submit из него удален.

**Comment by shining-mind** [comment]
В момент когда вызывается обработчик компонент уничтожен

```
{componentId: 'u9a3819da251ae', componentName: 'b-form', hook: 'destroyed'}
```

На узле form сохраняется обработчик для первого инстанса

<img width="693" alt="image" src="https://github.com/V4Fire/Client/assets/46344555/d84e8763-3331-4835-b4b5-685ee8b42705">

**Comment by shining-mind** [comment]
Если в примере первую кнопку сделать не функциональной, то проблема уходит:

```
< b-button @click = activeTab += 1 | v-func = false
	ActiveTab: {{activeTab}}

< b-form @onSubmitStart = console.log('onSubmit')
	< b-button :type = 'submit' | v-func = true
			Submit
```

**Comment by shining-mind** [comment]
При ре-рендере функционального компонента DOM узел остается неизменным. При обновлении компонента для DOM узлов внутри библиотеки Vue вызывается специальная функция `patchElement`. 

У формы в нашем примере есть два обработчика: `onSubmitStart` и `onSubmit`.

Обработчик `onSubmit` добавляется непосредственно в шаблоне `b-form`, а `onSubmitStart` извне, из-за этого
`onSubmitStart` попадает в массив `dynamicProps`.

Создается vnode, который имеет `patchFlag` равный 40 (8 = PROPS | 32 = HYDRATE_EVENTS).

С флагом 8 (PROPS) При вызове функции `patchElement` для каждого `dynamicProps` происходит вызов `patchProp` и как следствие обработчик обновляется.

Однако в полученном vnode, который имеет `type = b-form-functional` в `dynamicProps` нет обработчика `onSubmit`, поэтому обновление обработчика не происходит.

Если для данного vnode добавить к `patchFlag` 16 = FULL_PROPS, то обработчик submit будет обновляться.

**Comment by shining-mind** [comment]
Fixed in #1131
