### ISSUE TITLE
[v4] Использование asyncRender.iterate с очисткой элемента ломается из-за v-async-target на элементе

### ISSUE THREAD

**Issue by ann-arzamm** [V4Fire/Client#1183]
> Пример в ветке `issues/1183`

Если нужно реализовать вложенные вызовы `asyncRender.iterate`, и на очищаемом элементе есть `v-async-target`, то пересоздание элемента не происходит.

Пример:
```ts
< .&__container v-async-target
  < template v-for = _ in asyncRender.iterate(true, {filter: asyncRender.waitForceRender('item')})
    < .&__item v-async-target
      test
```
При вызове `asyncRender.forceRender()` должен быть пересоздан `&__item`, но `&__container` вместо этого пустой.

**Comment by boikovdv** [comment]
Данный пример не совсем корректный, поскольку у внутреннего async-target нет вложенного в него async-render
Если добавить еще 1 рендер, то все работает штатно.
Считаю что это починено в рамках #1184
