### ISSUE TITLE
Совместное использование пропа `ssrRendering` и одноимённой ss-константы

### ISSUE THREAD

**Issue by Dimeliora** [V4Fire/Client#1186]
Для предотвращения рендеринга компонента на стороне сервера при использовании SSR необходимо устанавливать не только проп компонента `ssrRendering` в значение `false`, но и значение константы `ssrRendering` в шаблоне компонента, также в значение `false` (по умолчанию она установлена в `true`). Это следует из реализации в шаблоне `i-block`:
```
- if !ssrRendering
	< template v-if = !ssrRendering
		+= self.render({wait: 'async.idle.bind(async)'})
			+= self.renderRootContent()

	< template v-else
		+= self.renderRootContent()

- else
	+= self.renderRootContent()
```

В противном случае, при использовании только пропа, будет предотвращён запрос данных компонента, но не рендеринг.
Следует предусмотреть реализацию уведомления при использования пропа `ssrRendering = false` без установки значения `false` ss-константе `ssrRendering`.

**Comment by shining-mind** [comment]
Да, такая проблема есть. Получается, что нельзя произвольным образом решить какой компонент рендерить на сервере, а какой - нет, при этом не изменив сам компонент.

**Comment by kobezzza** [comment]
С новым подходом становиться не актуально
