### ISSUE TITLE
Слушатель с группой `:suspend` работает некорректно

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1198]
После того как был вызван unsuspend все накопленные события должны быть выброшены единомоментно, ондако этого не происходит.

![Screen_Shot_2024-03-26_at_13 44 13](https://github.com/V4Fire/Client/assets/46344555/62e85157-982c-4f9f-a653-2f26521558a2)

UPD: проблема где-то на уровне в activated/deactivated хука / обработчика

**Comment by bonkalol** [comment]
![image](https://github.com/V4Fire/Client/assets/5569667/310aeb60-b6c9-4fd2-9b69-df6bcc900334)

так работает

**Comment by bonkalol** [comment]
![image](https://github.com/V4Fire/Client/assets/5569667/c5cb83f9-02da-403a-a497-998621f57713)

и так работает

**Comment by bonkalol** [comment]
но с actived+deactivated не пашет, разбираемся
