### ISSUE TITLE
Неверно обрабатывается ввод символов в b-input

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#12]
При изменении значения в инпуте происходит "запаздывание" присвоения значения, вследствие чего неправильно обрабатывается валидация поля (например, при отправке запроса на проверку будет отправлено значение с предыдущим введённым символом). Происходит это из-за того, что **значение присваивается после** того как сработало событие **onInput** и вызвалось соответственно событие actionChange, по которому вызывается валидация.

**Comment by kobezzza** [comment]
Поправлено
