### ISSUE TITLE
Наличие валидатора в инпуте не позволяет закрыть клавиатуру при вводе с мобильного устройства

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1203]
```snakeskin
< b-input :validators = ['required'] | :placeholder = 'Your text'
```

Можно запустить через npx static, а потом открыть в эмуляторе андройда http://10.0.2.2:8080/p-v4-components-demo.html

**Comment by boikovdv** [comment]
Не повторяется на android 14
Проявляется на android 12 и ниже.
