### ISSUE TITLE
Проверка совместимости компонента-директивы

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#1214]
Нужно проверить следующую гипотезу.

Допустим, у нас есть компонент на сервере

```
< b-example
```

Который просто создает разметку на основе шаблона, например,

```
< div.b-example
  < img src = foo.png
```

А на клиенте у нас используется вместо компонента директива

```
< .b-example v-example
```

Сделать это можно с помощью if на уровне SS

```
- if SSR
  < b-example
- else
   < .b-example v-example
```

И проверить, работает ли в таком режиме гидратация или ломается.

**Comment by shining-mind** [comment]
Ремарка: разметка будет точно разной т.к. компонент - это блок в методологии БЭМ, а директива - она используется в рамках существующего компонента. Стоит этот момент учесть, и как отключить собственные классы для `b-example`

**Comment by kobezzza** [comment]
Эксперимент вышел удачный. Будем масштабировать эту идею для ускорения SSR.
