### ISSUE TITLE
Гонка данных в b-dynamic-page и asyncRender

### ISSUE THREAD

**Issue by geopr** [V4Fire/Client#1262]
Открываем следующую страницу:

```ts
@component()
class pTest extends bDynamicPage {
  @hook('activated')
  protected redirect(): void {
    this.router?.replace('another-page');
  }
}
```

Происходит гонка данных: [вотчер](https://github.com/V4Fire/Client/blob/v4/src/components/base/b-dynamic-page/b-dynamic-page.ts#L600) изменения страницы отрабатывает раньше, чем `asyncRender` вызывает свой фильтр и [создает](https://github.com/V4Fire/Client/blob/v4/src/components/base/b-dynamic-page/b-dynamic-page.ts#L352) промис. Таким образом, в вотчере резолвится старый промис, а новый создается и висит

**Comment by kobezzza** [comment]
А сделай мне бранч с ошибкой тут

**Comment by shining-mind** [comment]
Создал пример в ветке `examples/1262`.

Шаги воспроизведения:
1. Запустить демо страницу
2. Сделать пуш в роутер два раза:
  ```
  document.getElementById('root-component').component.router.push('page2');
  document.getElementById('root-component').component.router.push('page3');
  ```

ФР: активная страница - page2
ОР: активная страница - page3

P.s. фикс Гоши дает ожидаемое поведение

**Comment by kobezzza** [comment]
Исправлено

**Comment by shining-mind** [comment]
https://github.com/V4Fire/Client/commit/1313406fc291300b53cf9005c55c371eac77ef5e
