### ISSUE TITLE
Перерендер b-dynamic-page отменяет будущие задачи рендера

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1263]
Если в b-dynamic-page происходит ререндер, то отменяются не только старые задачи, но и последующие.

TODO: создать ветку с примером

**Comment by shining-mind** [comment]
WIP Fix: https://github.com/V4Fire/Client/pull/1086

**Comment by kobezzza** [comment]
Исправлено

**Comment by shining-mind** [comment]
https://github.com/V4Fire/Client/commit/79724930e68fc4ee7a3550ad8a8a0d8ce40ca55c
