### ISSUE TITLE
Отличное от v3 поведение при изменении пропов у компонента

### ISSUE THREAD

**Issue by geopr** [V4Fire/Client#1268]
Как пример возьмем `b-dynamic-page`, у кого есть проп `pageProp`, который связан с системным полем `page`. В v3 при изменении пропа, не происходит перерендера компонента, а в v4 происходит

**Comment by kobezzza** [comment]
Это поведение Vue3 - вот пример https://play.vuejs.org/#eNqFks1O4zAUhV/lypu2AqVIM6sojGYGsZiR+BGwtIRCelMMjm3Z16UoyrtzbdPCgp9NFN9zHH/nOKP441y1iShq0YTOK0cQkKID3Zr1sRQUpPgljSQ1OOsJTuzgoPd2ACmqZVql3VKwxQC8mkbw2MNUfDPWZ0XurAkEvfL8PE6e+dGiKH00HSlroPPYEs4XMKYxC8lcbVod8eAgjSZpmmUhTVymIRyc5j28AmgyX91by+xlL9lr8sqs5wtO0mTkYr2LRHzi706r7pHt5Wg2neSXZlkMbG6W+0PEodiF/qYyAGlKYOetCxx4hb0yeJlW8xyPMetdUHp2WENBPSwj9rdRUw0z7i8nn7iuL9KPI5y1dF/51qzswCVOua338BSYqVfr6iFYwwny6ZydMymN/sKlW+AAey4pWq3t0/88Ix/xFY733GP3+MH8IWzTTIpLjwH9hivda9T6NVKRT6/Pccvve3Gwq6jZ/YV4hcHqmBiL7W80K8Z+58u0//J/yE3ehNMtoQm7UAk0d5n9UvA1puv8LPob7o/q5+4OuMXbDfr0TS6QhepITC/EvRfw

Не понятно так задумано ли, или это баг пока

**Comment by kobezzza** [comment]
Добавлю, что если заворачивать пропс в функцию-геттер, то нежеланный эффект уходит

https://play.vuejs.org/#eNqFUk1PGzEQ/SsjX0gE2iC1p2iD2iIqtVJbVDhaQstmNhi8tmWPQ9Bq/ztjOxs48HFZ2fPeeN57s4P47ly1jSiWog6tV44gIEUHujGblRQUpDiTRpLqnfUE57Z30HnbgxTVIt1StxRMMQB70gAeOxgL74jxowK31gSCTnn+rhJndjovSBdNS8oaaD02hLM5DKnMQCJX20ZHPD5OpVGaelGUJl2mJuyd5h6+AdRZ37KzlrXzK6uz/Qtkr8grs5nN2U+dhZeG20jEc7+1WrUP3FQEMOk8H+pFITC5XhxGiRMxWf8kOABpim3nrQtse42dMniZbrNsksUuJ7v05HAJP/dp7P2OHNIHnocB/jR0V/nGrG3Ppsec0WuxFFhDpzbVfbCGFedp7JU9KI3+n0vTWPBBhxSN1vbxd66Rj3gy1ds7bB/eqN+HXapJcekxoN9yhAeMGr9BKvDF1V/c8fkA9nYdNbM/AP9jsDrmRDLtRzRrlv2Kl9X+yn8fL/k6XOwITZhMJaE5y8yXgteW1vee9Re5X6qv0w44xZst+vQmB8hAdSrGZ0xdFMg=

**Comment by kobezzza** [comment]
Еще можно лечить через v-memo на рут узле

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/pull/1297
