### ISSUE TITLE
Пересмотреть destroyNode в async-render/iterate с учетом реализации рекурсивного $destroy

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1277]
https://github.com/V4Fire/Client/blob/b6894f4afccf8628bdff683fd49c67031f18ac51/src/components/friends/async-render/helpers/render.ts#L72-L90

Связанный issue: #1216

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/pull/1286
