### ISSUE TITLE
Не срабатывает хук `activated` при гидратации на клиенте

### ISSUE THREAD

**Issue by miniven** [V4Fire/Client#1325]
Сломалось после этого фикса: https://github.com/V4Fire/Client/commit/ea3781ca0e7d40b660fdb6300569b1baad65334a

Причина: при гидратации не вызывается `onPageChange`, страница не попадает в `keep-alive`, поэтому и хук не срабатывает. 

Было обсуждение по поводу того, должен ли вообще этот хук срабатывать при первом рендере страницы. Во Vue хук работает следующим образом: https://ru.vuejs.org/guide/built-ins/keep-alive.html#lifecycle-of-cached-instance

[Пример](https://play.vuejs.org/#eNp9U9tu2zAM/RVOwOAETe1i21PnBMvaArug67Dt0S+ewyRqZcnQxckQ5N9HSbbrbm0ebEg8h+ThRQe2bJq0dcguWW4qzRsLBq1rFoXkdaO0hQNoXMMR1lrVkBA1GaArVTedPc38xUdK3heykJWSxkJbCocw9xEmF9MArJ2sLFcSlLwSvHqYTOFQSIjUNPzPzoh59OQ8i5pIDV0s1o0oLdINIP/trKUwHyofhXJ08Rbh/yrPIh65XxGbpeBtdCVDUN6e8zU5FizKfA1vYD6Hi4It8lBN9M3Gznk2EsFmzBoqdM036b1RknoYSilYRd5coL5rfKmmYJexSI+VQqjdl2Cz2uGst1dbrB6esd+bvbcV7LtGg7rFgg2YLfUGbYRvfn7DPZ0HsFYrJ4h9AvyBRgnnNUbaRydXJHvEC2o/h3FzufllbvYWpemL8kI98xj41EiHvnEvlf4o9236LvjRnKmL/eqcWkIll7Q3LXV+NaPLrXKyO15j2SP/rGkhB+KE9my+iFL8biqBqVCbSVJHPJmSFPq8y5Bo7JRlUFEzKActHZfc8lJAcO7QUq4AW9R/wPIagVvghhb/nEuamtcWlNktUhya9X9ChiIS/1B6LaPinlez26KkNLVqxymu725JpFVP83UqS2FU9HOyKz9M6Imc1WPiQdCp5xhfC8AnpI2BndIiBM0zD4yeDTv+BT67f4w=), демонстрирующий, что `activated` срабатывает при первом рендере.

Если просто удалить проверку, которая была добавлена в коммите, то хук срабатывает, но возникают другие баги в `Analytics`. Их связь с этим хуком мне не очевидна.

Если я правильно понимаю, то `if (HYDRATION && !this.hydrated)` все же лишнее, потому что в методе `syncPageWatcher` есть два варианта: **либо** обработчик `onPageChange` уже задан и его нужно вызвать немедленно, **либо** обработчик `onPageChange` еще не задан и нужно подписаться на событие `onPageChange` и снова пытаться вызвать этот обработчик.

Как будто второй вариант — это как раз правильная логика для фазы гидратации: «обработчик `onPageChange` не задан, поэтому ждем событие `onPageChange`,  которое наступит после гидратации и уже там вызвать обработчик». Возможно, проверка `if (HYDRATION && !this.hydrated)` должна была предотвратить немедленный вызов `onPageChange`, но в итоге не происходит даже подписка на событие.

**Comment by shining-mind** [comment]
Fixed in #1326
