### ISSUE TITLE
В `v-attrs` часть кода не выполняется

### ISSUE THREAD

**Issue by misbiheyv** [V4Fire/Client#1336]
Условие никогда не выполняется, тк `componentCtx` устанавливается только после выполнения хука директивы `beforeCreate`
```ts
if (componentCtx != null && !isDOMEvent && Object.isFunction(attrVal)) {
	if (isOnceEvent) {
		componentCtx.$once(originalEvent, attrVal);

	} else {
		componentCtx.$on(originalEvent, attrVal);
	}
}
```

Вероятно, можно просто удалить, сделано для функциональных компонентов, но в них и без этго все работает. Выглядит как ненужный код, был создан в [этом](https://github.com/V4Fire/Client/commit/ed592298060c9e67e3af4edcb2e1d8384fe71ddd#diff-c15b5fe7cd63f754f2a93991657b5b596e02bb91bee426d14fc689fcbb41fade) коммите с багом (было `if isOnceEvent componentCtx.$on(originalEvent, attrVal)`)

**Comment by kobezzza** [comment]
Это был мертвый код - удалили
