### ISSUE TITLE
[disable-reactive-props] Измененный модификатор перезаписывается при обновлении родительского шаблона

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1366]
Если у дочернего компонента изменился модификатор, то при обновлении родительского шаблона он будет перезаписан на базовое значение из `ctx.provide.mods()`

Пример в ветке:  [`examples/1366`](https://github.com/V4Fire/Client/compare/disable-reactive-prop-2-new-init-force-props...examples/1366?expand=1)
1. Отметить чекбокс
2. Нажать "Submit"

ФР: чекбокс сбросил значение
ОР: чекбокс сохранил свое значение

**Comment by kobezzza** [comment]
Исправлено
