### ISSUE TITLE
[disable-reactive-props] если передать undefined в качестве значения, то модификатору не установится дефолтное значение  

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1372]
Например, возьмем b-button у которого есть модификатор `opened` с дефолтным значением `false`.

Если создать `< b-button :opened = undefined` и проверить `ctx.mods.opened` - то он будет также равен `undefined`

Пример в ветке `examples/1372`

**Comment by kobezzza** [comment]
Исправлено
