### ISSUE TITLE
Создание разных версий компонента по непонятным причинам

### ISSUE THREAD

**Issue by ItMaga** [V4Fire/Client#1446]
В версии клиента `4.0.0-beta.142` появилась проблема, что могут создаваться разные версии компонента. Это связано с наследованием параметров `functional` в декораторе `component`. Если у родителя задан: `@component({functional: {}})`, то все его потомки тоже будут функциональными по умолчанию.
 
- в ios - функциональный (что by design - верно), иногда обычный
- в android - обычный

На примере ios, если компонент является функциональным, по какой-то причине у него задается shapeFlag = 4 (STATEFUL_COMPONENT) и в этом случае рендер падает, потому что Vue ожидает там обычный компонент.

Вот таким образом выглядит vnode подобного компонента 
![image](https://github.com/user-attachments/assets/643196a8-5ab9-4bb1-9e20-e89442d28ec3)

Падает с ошибкой `TypeError: null is not an object (evaluating 'instance.exposed')` в функции getExposeProxy со следующим трейсом
```
TypeError: null is not an object (evaluating 'instance.exposed')
getExposeProxy — v2:37386
setRef — v2:34369
patch — v2:34956
mountChildren — v2:35128
processFragment — v2:35309
```

Обычный компонент создается со следующими данными и все корректно рендерится:
![image](https://github.com/user-attachments/assets/cf02b51e-537f-4c94-9159-a13b758836b7)

### Причина плавающего характера

Связано с тем, что у нас регистрация компонента происходит не сразу, а через `requestIdleCallback` https://github.com/V4Fire/Client/blob/90b6fe5867f089d0a8e10967bc1eac085f961718/src/core/component/decorators/component/index.ts#L122-L127
И попадаем в ситуацию, что при регистрации смарт компонента, какой-то из компонентов(обычный/функциональный), который нужен, может не успеть зарегистрироваться. 

Чтобы симулировать поведение, можно например отложить регистрацию для обычного компонента, а функциональный регистрировать сразу, тогда проблема с shapeFlag = 4, которая описана выше, будет воспроизводится стабильно. Пример кода:

```ts
		if (componentFullName === 'b-component-name-functional' || needRegisterImmediate) {
			registerComponent(componentFullName);

		} else {
			setTimeout(registerComponent.bind(null, componentFullName), 2000);
		}
```

**Comment by shining-mind** [comment]
Дисклеймер: до версии 4.0.0-beta.121 иногда компоненты создавались как функциональные, а иногда как обычные. Был баг в смарт-компонентах, который устранили, но видимо не до конца.
