### ISSUE TITLE
Удалить i-data из b-button

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1468]
Кнопка должна быть кнопкой, если надо сделать POST запрос, то нужно использовать форму.

**Comment by kobezzza** [comment]
Я против. Компонент b-button обслужавает множество кейсов и это очень удобно. Например, псевдоссылка дергающая провайдер или загрузка файла по кнопке. Проблем с этим нет, как и профита в удалении (компонент не станет проще или быстрее).

Если вопрос скорости и легкости, то надо сделать отдельно класс g-button

**Comment by shining-mind** [comment]
Это не семантично, нужно использовать form для этих целей. На практике в продукте - у нас эта функциональность не используется.

**Comment by kobezzza** [comment]
Это удобно. Вопрос закрыт.
