### ISSUE TITLE
[bVirtualScroll] События жизненного цикла

### ISSUE THREAD

**Issue by Zakhse** [V4Fire/Client#205]
Добавить отправку событий, позволяющих отреагировать извне на процессы в b-virtual-scroll.
Интересуют следующие:
- переход в состояние загрузки следующего чанка данных
- успешная загрузка чанка данных
- отрисовка загруженных данных

Возможно, будут полезными какие-то ещё.

Было бы хорошо по возможности связать их с существующими событиями (statusLoading, statusReady, dbChange).

**Comment by bonkalol** [comment]
- `startLoadingChunk` -> начал загрузку чанка эмитися на каждый поход в dataProvider
- `chunkLoaded` -> загрузил данные с сервера -> эмит события chunkLoaded с payload загруженным чанком
- `chunkRendered `-> зарендерил новую ленту
- `dbChange` -> загрузил данные с сервера и набрал на рендеринг -> мерж данных в один объект -> эмит события dbChange с payload смерженые загруженные чанки

**Comment by bonkalol** [comment]
- `chunkLoadingError` -> ошибка загрузки данных

Возможно:
- `chunkRenderError` -> ошибка рендеринга чанка

**Comment by bonkalol** [comment]
`dbChange` к сожалению не будет поддержано из некоторых тонкостей, поэтому вместо него будет событие `dataChange`

 Тонкости:
В кейсе когда произошла первая загрузка данных но чтобы зарендерить нужно сделать еще одну загрузку - непонятно в какой момент и с каким payload эмитить dbChange

**Comment by Zakhse** [comment]
> чтобы зарендерить нужно сделать еще одну загрузку
Это точно не баг, а фича? Возможно, следует поменять эту логику, а не отказываться от наименования события?

**Comment by bonkalol** [comment]
Триггерить `dbChange` со смерженными данными (все данные которые были загружены)
Добавить в `dataChange`, `chunkLoaded`, etc номер загружаемого чанка
