### ISSUE TITLE
Отрисовка элементов в b-virtuall-scroll. Обработка случая с большим количеством отфильтрованных данных.

### ISSUE THREAD

**Issue by KustovAA** [V4Fire/Client#231]
Когда в чанке после фильтрации остается мало данных, b-virtuall-scroll может прекратить рендер следующих чанков, посчитав, что данные кончились.

**Comment by bonkalol** [comment]
@KustovAA фикс в https://github.com/V4Fire/Client/tree/issue/231

**Comment by bonkalol** [comment]
Уехало в релиз 3.0.0-beta.272
В RC пойдет вместе с https://github.com/V4Fire/Client/pull/201
@KustovAA
