### ISSUE TITLE
[core/dom/inview] Использовать pull of observers в директиве

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#251]
Сейчас директива in-view на каждый обозреваемый элемент создает нового IntersectionObserver что является не эффективно по памяти, это можно передалать на пул обсерверов

- Вынести модуль, сделать его более user-friendly к использованию при прямом вызове, сейчас каждый раз приходится чистить через async.worker
- Обсервер будет выбираться по подходящему threshold с элементом с небольшой погрешностью
- Если элементу не нашлось intersection observer - новый intersect observer будет создан

**Comment by kobezzza** [comment]
Тут можно задачку разделить на две: абстрактный класс для пула обсерверов и собственно пул для in-view
