### ISSUE TITLE
[Tests] Покрытие тестами функционала i-блоков

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#253]
Необходимо создать компонент b-dummy и покрыть тестами базовые вещие, такие как модификаторы, дата провайдеры и т.д.

**Comment by bonkalol** [comment]
**Обновление статуса:**
b-dummy создан и наследуется от iData

**Comment by bonkalol** [comment]
https://github.com/V4Fire/Client/pull/420
Почти готово здлесь

**Comment by kobezzza** [comment]
Закрываю, т.к. есть отдельные задачи
