### ISSUE TITLE
[Tests] [Build] Перевод инфраструктуры с JS на TS

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#263]
## Что делаем:

- [x] Подключить TS node и алиасинг путей
- [x] ~~Поправить алиасинг путей чтобы избегать конфликтов модуль/пакет~~
- [x] Перевести на TS и зарефакторить хэплеры для компонентных тестов
- [ ] ~~Проверить как сейчас работает `include` в `JS`, `import` в `styl` и подключение шаблонов в `SS`, в частности посмотреть на пути которые указываются при подключении, идентичны ли они старым, нужно будет сохранить консинстентность (чтобы и в ts и ss, styl импорты были одинаковыми)~~
- [ ] Перевести на TS и зарефакторить модуль запуска компонентых тестов 
- [ ] Перевести на TS компонентные тесты
  - [x] cookies
  - [ ] inView
  - [ ] vImage
  - [ ] bBottomSlide
  - [ ] bRouter
  - [ ] bButton
  - ...
  

Тестирование:
- [x] Проверить что работают компонентные тесты на TS и JS
  - [x] Запуск одного TS теста с билдом
  - [x] Запуск одного JS теста с билдом
  - [x] Запуск одного TS теста без билда
  - [x] Запуск одного JS теста без билда
- [x] Проверить что gulp таски на TS и JS
- [ ] Проверить что сборка работает на TS и JS
- [ ] Проверить что `super/i-static-page/modules/ss-helpers` работает на TS и JS
- [x] Проверить что проект корректно собирается
- [ ] Проверить что в дочерних проектах тесты работает на TS и JS
- [x] Проверить что в дочерних проектах овверайды хелперов тестов работают
- [x] **Тесты успешно проходят в v4fire/core**
- [x] **Тесты успешно проходят в v4fire/client**
- [x] **Тесты успешно проходят в edadeal/core**
- [ ] **Тесты успешно проходят в edadeal/cb**

## МРы

[v4fire/client](https://github.com/V4Fire/Client/pull/693)
[v4fire/core](https://github.com/V4Fire/Core/pull/277)
~~[@pzlr/build-core](https://github.com/pzlr/build-core/pull/19)~~

#### Проблема:
`h.utils.something cannot read property something of undefined`

Возникает в JS файлах при импорте TS файлов через include например

#### Решение:
Поправить импорт модуля

```
const
  h = include('tests/helpers').default;
```

-----

#### Проблема:

Начала падать какая-то спеки, хотя другие проходят норм

#### Решение:

1. Возможно было удалено какое-то API, свертись с CHANGELOG и убедитесь что не используете удаленое API

-----

#### Проблема:

Проект собирается с ошибками, TS светит на импорты

#### Решение:

Убедитесь что у вас собран свежий tsconfig

----

#### Проблема:

Неправильный импорт модуля `config`

#### Решение:

Проблема заключается в резолвинге путей и ts-node, из-за того что в проекте есть config/index.ts импортится он вместо config модуля

Как пофиксить:

Делаем алиас в package.json для config:

```
"@config/config": "npm:config@^1.31.0",
```

----

#### Проблема:

Не работает gulp таска build:tsconfig

#### Решение:

Эта gulp таска была удалена, на ее смену пришел обычный node js скрипт который собирает tsconfig

__package.json__
```
"tsconfig": "node node_modules/@v4fire/core/build/tsconfig"
```

**Comment by kobezzza** [comment]
А это реально надо?

**Comment by bonkalol** [comment]
Думается что нет, хватит // @ts-check и index.d.ts @kobezzza

**Comment by bonkalol** [comment]
Но я бы пока поставил research label и оставил пока, посмотрим еще немного, по фидбеку от клиентов

**Comment by bonkalol** [comment]
Закрываю, так как `// @ts-check` и `tests.d.ts` хватает полностью для автокомплита

**Comment by bonkalol** [comment]
### Возникающие проблемы и их решение

#### Проблема:
`h.utils.something cannot read property something of undefined`

Возникает в JS файлах при импорте TS файлов через include например

#### Решение:
Поправить импорт модуля

```
const
  h = include('tests/helpers').default;
```
