### ISSUE TITLE
[iBlock.vdom] createElement и vdom.render - компоненты без $parent

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#270]
При использовании createElement и vdom.render компоненты не получают `$parent` свойство - оно undefined

Воспроизводится только с обыкновенными компонентами, у функциональных `$parent` устанавливается корректно

В `src/core/component/construct/index.ts`
`component.unsafe.$root.unsafe.$remoteParent` - `undefined`
`component.unsafe.$root.$remoteParent` - возвращает корректное значение

В последней beta версии клиента это работает корректно

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/pull/276
