### ISSUE TITLE
Cannot set property page of #<Object> which has only a getter

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#271]
Cannot set property page of #<Object> which has only a getter

![image](https://user-images.githubusercontent.com/5569667/84520559-6aa1e980-acdc-11ea-80c7-2725a43fa457.png)

Ошибка происходит в `Object.mixin` на 131 строке, при попытке установить значение в геттер `page`

![image](https://user-images.githubusercontent.com/5569667/84521621-f700dc00-acdd-11ea-8c03-973dcf288396.png)

Проблема воспроизводится начиная с `rc27`

**Comment by kobezzza** [comment]
@bonkalol А точно клиен тпоследний? Я это правил вроде

**Comment by bonkalol** [comment]
Не воспроизводится на последнем RC (rc30)
