### ISSUE TITLE
[bVirtualScroll] Не грузятся элементы при фильтрации

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#279]
**Описание проблемы:**
При фильтрации на клиенте отображается пустая выдача, хотя есть данные и возможность запросить ещё.

**Пример как воспроизвести:**
Установить chunkSize = 5.
В первом же полученном чанке отфильтровать офферы, оставить только один.
Запросы за следующими офферами не уходят

**Comment by bonkalol** [comment]
https://github.com/V4Fire/Client/pull/293/files#diff-d643f23d561f636fa087b37605c69c3bR190
Вот здесь добавлен тест на это и эта бага не воспроизводится, закрываю issue, если будет больше деталей или будет понятно как воспроизвести - новую issue
