### ISSUE TITLE
[bVirtualScroll] При total < chunkSize отправляется лишний запрос за заведомо пустым чанком

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#280]
**Описание проблемы:**
Сервер прислал total < chunkSize и несколько предложений, bVirtualScroll отправил ещё один пустой запрос.

**Дополнительная информация:**
Компоненту была передана функция для фильтрации данных, но ничего не было отфильтровано

**Comment by bonkalol** [comment]
Закрываю, `total` передается для использования клиенту, а сам компонент ничего с ним не делает
