### ISSUE TITLE
[bVirtualScroll] Не совпадают данные в полях lastLoadedData и lastLoadedChunk.normalized

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#281]
**Описание проблемы**
`lastLoadedData` помечен deprecated, но в некоторых случаях вызов функции-хелпера `getRequestParams`  (`src/base/b-virtual-scroll/modules/helpers.ts`) производится с этим полем в объекте `merge`, передаваемым третьим аргументом:
`getRequestParams(undefined, undefined, {lastLoadedData: val.data})`

В итоге в результирующем объекте, возвращаемом из `getRequestParams` значение в `lastLoadedData` есть, а в `lastLoadedChunk.normalized` нет.

**Ожидаемый результат** 
В полях должно быть одно и то же значение.

**Comment by dmitrybrovka** [comment]
В примере с вызовом 
`getRequestParams(undefined, undefined, {lastLoadedData: val.data})`
В методе `bVirtualScroll.initRemoteData` eсть помимо конвертированных данных (val.data) доступ к сырым данным, но она не передаётся в `lastLoadedChunk.raw`

**Comment by bonkalol** [comment]
Из-за того что везде используется `dbConverter` для нормализации данных невозможно достать сырой объект в initRemote

Поэтому я добавил призыв в случае если используется `dbConverter` для нормализации данных в формат подходящий компоненту, заменить его на `componentConverter`, в случае если `componentConverter` будет предоставлен, raw объект будет передан клиенту
