### ISSUE TITLE
Позволить работать convertStateToRouterReset, когда нет изменений в syncRouterState

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#284]
**Проблема**
Сейчас геттер needRouterSync проверяет наличие syncRouterState и не даёт выполнить логику  convertStateToRouterReset, когда разработчик не указывал syncRouterState отличный от инстанса

```
...
async resetRouter(): Promise<boolean> {
 //#if runtime has bRouter
 if (!this.needRouterSync) {
  return false;
 }
...
```

```
get needRouterSync(): boolean {
 return baseSyncRouterState !== this.instance.syncRouterState;
}
```

**Проверить**
convertStateToStorageReset

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/pull/304
