### ISSUE TITLE
[Async] [iData] Зависание провайдеров при вызове метода reload

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#328]
Обнаружил кейс в котором промис возвращаемый методом `iData.prototype.reload`  никогда не резолвится и не реджектится (то есть зависает)

Проблема всплывает из-за `catch` в методе `initLoad`

1. Вариант с которым работает корректно
```typescript
if (needRequest) {
	// Здесь код
	.then((data) => {
		void this.lfc.execCbAtTheRightTime(() => this.db = this.convertDataToDB<this['DB']>(data), label);
		return callSuper();
	}, (err) => {
		stderr(err);
		return callSuper();
	});
```

2. Вариант с которым зависает
```typescript
if (needRequest) {
	// Здесь код
	.then((data) => {
		void this.lfc.execCbAtTheRightTime(() => this.db = this.convertDataToDB<this['DB']>(data), label);
		return callSuper();
	})
	.catch((err) => {
		stderr(err);
		return callSuper();
	});
```

Окружение в котором воспроизводится:
**@v4fire/client**: 60rc
**@v4fire/core**: 3.27.0

Как воспроивезсти:
Напиши в личку я расскажу

**Comment by kobezzza** [comment]
Было исправлено в @v4fire/core
