### ISSUE TITLE
[Router] В webkit 14 тесты роутера падают с ошибками

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#329]
`ctx.route.meta.content` поле `meta` всегда `undefined`

Пробовал запускать на macbook результат такой же, вполне возможно что это какой-то баг из-за того что webkit 14 до сих пор в статусе TP, но лучше бы это проверить, так как релиз webkit 14 очень близко

**Comment by kobezzza** [comment]
Падают не только в WebKit, у меня периодически падало во всех браузерах (иногда проходит). Какая то гонка состояний. Я склонен думать, что это какой то баг в PW. Но по хорошему надо на версии 1.2.1 собрать версии браузеров из 1.4 чтобы убедится в этом.

**Comment by kobezzza** [comment]
Выдайте медальку авторам Playwright:

вчера убил целый день разбираясь почему с обновлением версии PW сдали падать тесты роутера. Ошибки на которых падало были из серии, что все свойства объектов стали ссылаться сами на себя. В общем мучался. Сегодня Богдан заменил

```
it('checking the .route property', async () => {
 expect(await root.evaluate(({route}) => route)).not.toBeNull();
});
```

на

```
it('checking the .route property', async () => {
	expect(await root.evaluate(({route}) => route != null)).toBeTrue();
});
```

И ВСЕ тесты стали работать. Примечательно, что этот тест проходит в обоих вариантах.

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/pull/392
