### ISSUE TITLE
[Build] Ошибка при подключении картинки из assets/img в styl файле

### ISSUE THREAD

**Issue by xdan** [V4Fire/Client#336]
Можно воспроизвести тут 
```bash
npx @v4fire/cli make app pol && cd pol && npm run build
```

в styl файле подключается картинка 
```styl
background img("assets/img/v4fire.png")
background-size cover
```

но в сборку попадает как 
![image](https://user-images.githubusercontent.com/794318/93752239-078eef80-fc07-11ea-9517-78352e14a3f8.png)

**Comment by kobezzza** [comment]
Исправлено
