### ISSUE TITLE
[core/component/render-function] Падает рендеринг

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#434]
При рендере с помощью `globalThis.renderComponents` падает отрисовка. Это происходит из-за того что `tagName` здесь бывает `undefined` в случае со слотами и из-за этого падает код

![image](https://user-images.githubusercontent.com/5569667/99182987-bbb18000-2749-11eb-84c8-3cdf9843e5e7.png)

Воспроизводиться не только с renderComponents но и при обычном рендере

**Comment by kobezzza** [comment]
Исправлено.
