### ISSUE TITLE
Не проставляются data-атрибуты в композитных компонентах

### ISSUE THREAD

**Issue by ExactlyNoSense** [V4Fire/Client#437]
Если композитный компонент отрисовать через '@', то при отрисовке у него не будет указанного data-атрибута. Из-за этого такой компонент нельзя найти в тестах через `h.dom.getRef`.

Пример:
```
< @b-icon -test-ref = icon
```

При запуске теста data-атрибуте не будет на элементе. Если '@' убрать, то атрибут у элемента появится

**Comment by kobezzza** [comment]
Исправлено.
