### ISSUE TITLE
Не срабатывает линковка prop и field

### ISSUE THREAD

**Issue by gretzkiy** [V4Fire/Client#438]
Добавить в компоненте связанные свойства класса (prop и field).

```js
@prop({type: String, default: 'this is the default value'})
testValueProp!: string;

@field((ctx) => ctx.sync.link((v: string) => {
	console.log(v);
	return v;
}))

testValue!: string;
```

Передать в компонент свойство по имени филда

```
< b-my-component &
	:testValue = 'this is the passed value'
.
```

В консоли всегда будет `'this is the default value'`

**Версия пакета** `3.0.0-rc.89`

**Comment by bonkalol** [comment]
Пока непонятно, надо дебажить

**Comment by kobezzza** [comment]
Не получается воспроизвести
