### ISSUE TITLE
[inView] Стратегия MutationObserver не срабатывает в кейсе, когда элемент зарендерился вне экрана

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#440]
Если элемент был отрисован вне области видимости, и попадает в неё после того как пользователь проскроллил родительский элемент, директива не срабатывает. Если же оставить в таком положении и проскроллить страницу, чтобы элемент скрылся, а затем вернуться к элементу, директива сработает.

Баг обнаружен на устройстве `iPhone SE` под управлением `iOS 11.0.1`. В `b-slider` добавляются элементы с директивой `v-analytics` и параметрами `inViewOptions`.

**Comment by bonkalol** [comment]
Думаю ради такого кейса и исключительно для ios 11 нет смысла погружаться в баг и придумывать какое-то решение (пока непонятно насколько сложное)

Хочу закрыть с "не будет исправлено"

@dmitrybrovka что думаешь?

**Comment by bonkalol** [comment]
Обсудили с @dmitrybrovka , решили закрыть
