### ISSUE TITLE
Получение модификатора через геттер m вызывает перерендер только один раз

### ISSUE THREAD

**Issue by gretzkiy** [V4Fire/Client#448]
Если использовать в шаблоне компонента для получения значения модификатора геттер `m`, шаблон обновляется только при первом изменении этого модификатора. Последующие изменения модификатора не вызывают перерендер.

В компоненте:

```typescript
static readonly mods: ModsDecl = {
	testMod: [
		['one'],
		'two'
	]
};

protected onOneClick(): void {
	void this.setMod('testMod', 'one');
}

protected onTwoClick(): void {
	void this.setMod('testMod', 'two');
}
```

В шаблоне:

```
< b-button @click = onOneClick
	One

< b-button @click = onTwoClick
	Two

{{ m.testMod }}
```

Только при первом нажатии на кнопку значение модификатора обновится в шаблоне

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/releases/tag/v3.0.0-rc.107
