### ISSUE TITLE
[tests] [config] Добавить в конфиг переменную для аргумента page

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#466]
Сейчас дефолтное значение `page` захардкожено в коде команды `gulp`. При его отсутствии во время запуска тестов в дочерних слоях код упадёт с ошибкой в совершенно другом месте без указания информации о том что это произошло из-за отсутствия аргумента.

**Comment by kobezzza** [comment]
Сделано, параметр `build.demoPage`
