### ISSUE TITLE
sync.link('route') Некорректно поведение

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#470]
Есть декларация системного поля в котором происходит синхронизация с полем `route`

```typescript
	@system((ctx) => ctx.sync.link('route', {deep: true, withProto: true}, (v: Dictionary) => {
		debugger;
		return ctx.field.get('query.prop', v);
	}))
	protected someTest?: Stage;
```

**Ожидается:** при повторном пуше на эту же страницу но с изменеными параметрами произойдет сихнронизация и функция будет вызвана

```typescript
$0.component.router.push('some-page', {query: {prop: 'view'}})
```

**Фактически:** Функция синхронизации вызывается только на старте

**Comment by bonkalol** [comment]
Делается это все на странице (наследник iDynamicPage)
Пробовал и через r.route и через @watch('route'), результата не было

То есть полный кейс:
С одной страницы (page-1) переход на другую (page-2) -> sync.link вызывается норм
Если оказавшись на странице page-2 опять сделать пуш на нее же , но с другими параметрами, `sync.link` вызван не будет

**Comment by kobezzza** [comment]
Исправлено в rc.137
