### ISSUE TITLE
[Tests] Починить b-tree тест

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#498]
https://github.com/V4Fire/Client/pull/478/checks?check_run_id=2102916364

Сейчас частенько флапает, возможно это не флап а бага, стоит разобраться и либо пофиксить тест, либо зарепортить багу

**Comment by dmitrybrovka** [comment]
Должно пофикситься в #318

**Comment by bonkalol** [comment]
Убрал из релиза 3.0.0, так как судя по всему это просто флап теста, идет в очередь
