### ISSUE TITLE
Вотчинг через геттер дружественного класса

### ISSUE THREAD

**Issue by gretzkiy** [V4Fire/Client#505]
Дружественный к корневому компоненту класс:

```typescript
export default class DataManager extends Friend {
  get data(): any {
    return this.r.watchableData.data;
  }
}
```

Корневой компонент:

```typescript
export default class pRoot extends iRoot {
  @field()
  watchableData: Dictionary = {};

  @system((ctx) => new DataManager(ctx))
  readonly dataManager!: DataManager;
}
```

Компонент, в котором есть геттер на данные:

```typescript
export default class bMyComponent extends iBlock {
  @computed({dependencies: ['r.dataManager.data']})
  protected get someData(): any {
    return this.r.dataManager.data;
  }
}
```

В таком случае в компоненте кэш геттера `someData` не будет инвалидироваться, и его значение не будет меняться при обновлении `r.watchableData.data`. Даже если указать у геттера `@computed({dependencies: ['r.watchableData.data']})`, то есть зависимость напрямую на field в корневом компоненте, геттер `someData` не будет инвалидироваться

**Comment by kobezzza** [comment]
Вариант с `@computed({dependencies: ['r.watchableData.data']})` поправил, теперь должно работать.

Второй способ через монтирование внешнего объекта наблюдения:

```js
export default class bMyComponent extends iBlock {
  @computed({watchable: true})
  protected get someData(): any {
    return this.r.dataManager.data;
  }
}
```
