### ISSUE TITLE
[asyncRender] [moduleLoader] Не грузится компонент, вставляемый повторно с другим условием загрузки

### ISSUE THREAD

**Issue by dmitrybrovka** [V4Fire/Client#518]
В шаблон рутового компонента добавлен следующий код:

```
+= self.loadModules('base/b-foo', { &
	renderKey: 'b-foo',
	wait: "localEmitter.promisifyOnce.bind(null, 'b-foo')"
}) .
	< b-foo ref = foo
```

В шаблон одного из компонентов внтури страницы:

```
+= self.loadModules('base/b-foo', { &
	renderKey: 'b-foo',
	wait: "localEmitter.promisifyOnce.bind(null, 'b-foo')"
}) .
	< b-foo ref = componentFoo | :bla = 'bar'
```

Модуль из второго листинга вообще не грузится при возникновении указанного события, а только при возникновении события из первого листинга. 
Сейчас проблема решается использованием `globalEmitter`

**Comment by kobezzza** [comment]
Исправлено.
