### ISSUE TITLE
При использовании self.loadModules параметр `wait` отрабатывает только для первого компонента 

### ISSUE THREAD

**Issue by agent-bo-007** [V4Fire/Client#535]
При использовании self.loadModules 
```
// в шаблоне b-any-item:
+= self.loadModules('base/b-any-control', { &
    renderKey: 'b-any-control',
    wait: "localEmitter.promisifyOnce.bind(null, 'b-any-control')"
}) .
```

```
< b-any-item // - module-loader сохраняет wait для модуля в кэше
< b-any-item // - теперь этот и последующие компоненты ждут срабатывания параметра wait у первого b-any-item
```

На текущий момент может быть решено бросанием события через globalEmitter

**Comment by kobezzza** [comment]
Какая версия V4? Я совершенно точно это давным давно правил.

**Comment by agent-bo-007** [comment]
Вроде свежая. Там же короче cache - просто мапа, где ключ - id модуля. При первом вызове `moduleLoader` -> `add`, `module` сохраняется в кэш, и потом следующие модули с таким же `id` - не сохраняются. Соответсвенно в кэше хранится единственная копия `module`, с единственным `wait` от первого компонента. Поэтому когда срабатывает `wait` у следующего компонента - ничего не происходит, т.к. при первом вызове `resolveModule` вешается ожидание на первый и зарегистрированный `wait`

Я сначала не разобрался, начал править `resolveModule`, чтобы как-то это разрулить. Но раз там проблема оказалась в механизме кэширования - непонятно, как лучше поправить

**Comment by kobezzza** [comment]
Исправлено
