### ISSUE TITLE
Теряется часть символов при быстром вводе с клавиатуры для  b-input

### ISSUE THREAD

**Issue by agent-bo-007** [V4Fire/Client#543]
В консоли куча ошибок вида: 
```
There is too frequent redrawing of the component "b-input" (# 163; 88ms). {path: "valueStore", value: "1323", oldValue: "132"}
```

**Comment by kobezzza** [comment]
Это не ошибки, а тебе варнинг, что у ты замучал свой стейт, что он делает супер частые перерисовки. Скорее всего у тебя где-то что-то не так.

**Comment by agent-bo-007** [comment]
https://github.com/V4Fire/Client/pull/533/files
При вводе в инпут, может быть навешен модификатор `progress` на родительский компонент, который из-за capture начинает перехватывать и блокировать события у инпута
