### ISSUE TITLE
Убрать кэширование с геттера `component` в `b-dynamic-page`

### ISSUE THREAD

**Issue by agent-bo-007** [V4Fire/Client#547]
Поскольку сейчас рендеринг компонента происходит асинхронно, зависимость от свойства `page` может вызвать кэширование неверного значения `undefined` для геттера `component` в `b-dynamic-page`.

**Comment by kobezzza** [comment]
Но ведь этот геттер не кешируется (cache: false)

**Comment by kobezzza** [comment]
Хм, кажется этот флаг не работает. Проверю.

**Comment by kobezzza** [comment]
Исправлено, опубликую фикс вместе с rc.199
