### ISSUE TITLE
Другой корневой элемент для asyncRender.waitForceRender

### ISSUE THREAD

**Issue by gretzkiy** [V4Fire/Client#570]
Сейчас при передаче названия элемента, который нужно удалить, в `asyncRender.waitForceRender`, этот элемент ищется через `block.element`, который использует название компонента в качестве корневого элемента.
При этом некоторые элементы имеют другое название корневого компонента, например, при использовании `vdom.bindRenderObject`, и с ними не получается работать при текущем api `waitForceRender`. Прокидывать объект элемента в `waitForceRender` тоже не очень удобно, потому что в момент первоначального рендера поле `block` компонента может быть еще не инициализировано, и невозможно его использовать для поиска элемента.

**Comment by kobezzza** [comment]
Сделано в V4Client v3.0.0-rc.209
