### ISSUE TITLE
Не прокидываются параметры в роутах через alias

### ISSUE THREAD

**Issue by Razdva122** [V4Fire/Client#591]
При использовании параметров в пути алиаса, они не доходят до основного компонента

**Code**
```
'srch-sku': {
	path: '/search/:citySlug?/products/:uuid',
	load: () => import('pages/p-srch-sku'),
	component: 'p-srch-sku'
},

'web-srch-sku': {
	path: '/:citySlug?/products/:uuid',
	alias: 'srch-sku',
}
```

**Expected behavior:**

/search/moscow/products/randomUUID работает точно так же как /moscow/products/randomUUID

**Actual behavior:**

На /search/moscow/products/randomUUID все работает корректно

На /moscow/products/randomUUID получаю ошибку `Expected "uuid" to be a string`

**Comment by kobezzza** [comment]
Исправлено
