### ISSUE TITLE
[i-input-text] Поддержка атрибутов

### ISSUE THREAD

**Issue by savintsev** [V4Fire/Client#681]
Появилась потребность добавить `b-input` атрибуты `inputmode` и `pattern`. Не удалось реализовать, потому что они не поддерживаются в `super/i-input-text/i-input-text.ts`.
Необходимо добавить в `i-input-text` поддержку этих атрибутов, или произвольных атрибутов со значениями.

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Client/tree/master/src/super/i-input#attrsprop
