### ISSUE TITLE
new Vue().mount на вход получает 10 vnode а возвращает 12 узлов два из которых текстовые узлы

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Client#777]
Сейчас данная проблема решается фильтрацией от текстовых узлов в b-virtual-scroll, но нужно общение решение. Чтобы получить общее решение нужно прогнать солидную кучу тестов которая еще не запускает на новом V4.

https://github.com/vuejs/core/issues/6061

**Comment by ann-arzamm** [comment]
Та же проблема в b-ads-builder: при передаче на отрисовку массива из одного элемента, возвращается 3 - 1 нужный и 2 текстовые ноды, что ломает компонент.
