### ISSUE TITLE
Перенос теста b-bottom-slide на TS в рамках V4 

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#804]
https://github.com/V4Fire/Client/tree/v4/src/components/base/b-bottom-slide

Необходимо переписать тесты на ТС для этого компоненты. Обрати внимание, что из-за BR-ов в V4 сам тест тестов нужно обновить + я бы хотел порефакторить сами тесты, чтобы они были больше в стиле BDD (тест как документация).

**Comment by shining-mind** [comment]
Implemented in #815
