### ISSUE TITLE
Компонент использует геттер супер-класса с `@computed({cache:true,//...})`

### ISSUE THREAD

**Issue by Gannicus91** [V4Fire/Client#856]
Есть супер-класс c геттером

```ts
@component()
class Foo extends iBlock {
  get foo(): string {
    return 'foo';
  }
}
```

Он переопределяется

```ts
@component()
class Bar extends Foo {
  @field()
  n: number = 4;

  @computed({cache:true, dependencies: ['n']})
  override get foo(): string {
    return String(this.n);
  }
}
```

Компонент наследник при обращении к геттеру `this.foo` возвращает значение родителя - `'foo'`

При установке `cache: false` в декораторе `@computed` все в порядке

коммит на котором замечена ошибка `1c615f09645788c363686c414db9b6968fa17164`

**Comment by shining-mind** [comment]
Чтобы воспроизвести баг в указанном коммите, надо запуститься в эмуляторе под android. Обнаружил, что если в родителе геттеру задать `@computed({cache:true})`, то баг устраняется.

**Comment by shining-mind** [comment]
Когда у родительского геттера не задан кэш, он попадает в группу `accessors`, а дочерний геттер в группу `computedFields`:

https://github.com/V4Fire/Client/blob/2666b456ac4b5b470e952715c85d3c3e3079d9a8/src/core/component/decorators/base.ts#L74-L82

**Comment by shining-mind** [comment]
В ветке v4 баг тоже есть, однако вместо "foo" будет возвращено "undefined". Если родительскому полю задать `cache = true`, то проблема тоже устраняется.

**Comment by shining-mind** [comment]
Master fix: https://github.com/V4Fire/Client/pull/858
