### ISSUE TITLE
Написать тесты для директивы attrs

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#949]
Тесты должны покрывать все основные кейсы из доки и быть написанными в BDD стиле.

https://github.com/V4Fire/Client/tree/v4/src/core/component/directives/attrs

Дока про тесты - https://github.com/V4Fire/Client/tree/v4/docs/tests

Пример тестов другой директивы - https://github.com/V4Fire/Client/blob/v4/src/components/directives/in-view/test/unit/main.ts

**Comment by shining-mind** [comment]
@kobezzza тесты для директивы достаточны? Закрываем?
