### ISSUE TITLE
Сбрасывается фокус при вводе текста в < b-input при использовании валидаторов

### ISSUE THREAD

**Issue by savintsev** [V4Fire/Client#950]
В версии v4v4 при использовании валидаторов у `< b-input`  невозможно вводить текст.

Пример: `< b-input :validators = ['required']`

Текущее поведение: при использовании любых валидаторов после ввода одного символа input теряет фокус и приходится снова ставить фокус в поле чтобы продолжить ввод.

Ожидаемое поведение: в инпут можно свободно вводить текст, валидация проиходит не сбрасывая фокус с инпута

**Comment by kobezzza** [comment]
Исправлено
