### ISSUE TITLE
Написать тесты для модуля resize-watcher

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#965]
https://github.com/V4Fire/Client/tree/v4/src/core/dom/resize-watcher

Там есть старые тесты, на них можно подглядывать, но не более, а потом их удалить :)

Тесты пишем в BDD стиле, каждая спека должна служить документацией, а не только тестом.

Пример теста модуля - https://github.com/V4Fire/Client/blob/v4/src/core/cookies/test/unit/main.ts

**Comment by Dimeliora** [comment]
Выполнено: [#1001](https://github.com/V4Fire/Client/pull/1001), [#1009](https://github.com/V4Fire/Client/pull/1009)
