### ISSUE TITLE
Зарефакторить тесты bRouter

### ISSUE THREAD

**Issue by kobezzza** [V4Fire/Client#966]
https://github.com/V4Fire/Client/tree/v4/src/base/b-router

Тесты компонента написаны не очень удачно. Нужно избавиться от глобального конфига роутера и чтобы каждый тест содержал в себе собственную декларацию, чтобы служить как документация.

Частично работа уже проделана - 

https://github.com/V4Fire/Client/blob/v4/src/components/base/b-router/test/unit/transition/parameters.ts
https://github.com/V4Fire/Client/blob/v4/src/components/base/b-router/test/unit/transition/events.ts

Вот в таком же русле обновить все + подумать над описание спек, там где это необходимо

**Comment by Dimeliora** [comment]
Выполнено: [#1033](https://github.com/V4Fire/Client/pull/1033)
