### ISSUE TITLE
Реализовать getSSRProps во всех кастомных директивах

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#992]
Контекст: https://vuejs.org/guide/scaling-up/ssr.html#custom-directives

Сейчас при SSR мы все компоненты компилируем в VUE шаблон вида `<component :is = {tag}>`, это приводит к тому, что Vue компилирует следующиий код:

```js
_ssrRenderVNode(_push, _createVNode.call(_ctx,_resolveDynamicComponent.call(_ctx,"b-button"), {
 // props
}, {
  default: _withCtx.call(_ctx,(_, _push, _parent, _scopeId) => {
    if (_push) {
      _push(`Да, мне есть 18`)
    } else {
      return [
        _createTextVNode.call(_ctx,"Да, мне есть 18")
      ]
    }
  }),
  _: 1 /* STABLE */
}), _parent, _scopeId)

``` 

Тут важно обратить внимание на первую ветвь `if (_push) { ... }` в этом случае генерация HTML на сервере происходит просто через конкатенацию строк, во втором случае создаются `vnode`.

Непонятно по какому принципу срабатывает условие `if (_push)`, но при конкатенации строк в кастомных директивах не будет работать ничего кроме getSSRProps, потому надо этот кейс обработать.

**Comment by kobezzza** [comment]
Сделано в v4-ssr-speedup
